### ISSUE TITLE
certify error

### ISSUE THREAD

**Issue by yuchongy1** [quanlin-wu/dmae#1]
Hi,

I tried to reproduce the certify results on CIFAR-10 and got the following error:

```
Traceback (most recent call last):
  File "certify_cifar10.py", line 204, in <module>
    main(args)
  File "certify_cifar10.py", line 185, in main
    test_stats = certify_evaluate_dist(data_loader_val, smoothed_classifier, device, threshold, args.num)
  File "/home/yuchongy1/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
Traceback (most recent call last):
  File "certify_cifar10.py", line 204, in <module>
    main(args)
  File "certify_cifar10.py", line 185, in main
    test_stats = certify_evaluate_dist(data_loader_val, smoothed_classifier, device, threshold, args.num)
  File "/home/yuchongy1/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/gpfs/projects/punim1723/dmae/engine_finetune.py", line 298, in certify_evaluate_dist
    return func(*args, **kwargs)
  File "/data/gpfs/projects/punim1723/dmae/engine_finetune.py", line 298, in certify_evaluate_dist
    output, radius = model.certify(images, 100, num, 0.001, 1000, target.item())
  File "/data/gpfs/projects/punim1723/dmae/util/smooth.py", line 40, in certify
    output, radius = model.certify(images, 100, num, 0.001, 1000, target.item())
  File "/data/gpfs/projects/punim1723/dmae/util/smooth.py", line 40, in certify
    counts_selection = self._sample_noise(x, n0, batch_size)
  File "/data/gpfs/projects/punim1723/dmae/util/smooth.py", line 96, in _sample_noise
    predictions = self.base_classifier(noisy).argmax(1)
  
RuntimeError: Given normalized_shape=[768], expected input with shape [*, 768], but got input of size[100]
RuntimeError: Given normalized_shape=[768], expected input with shape [*, 768], but got input of size[100]
```

I follow the instructions mentioned in FINETUNE.MD. 

I printed the shape of "noisy", which is [100, 3, 224, 224].

Could you please help?

**Comment by quanlin-wu** [comment]
Sorry to answer your question so late. You said that the bug happend when you run certify_cifar10.py. In fact, 768 is the embedding dimension of  ViT Base, I think the problem should lies in 'models_vit.py', likely to be the nn.LayerNorm.  You need to check the version of 'timm', our version is 0.5.4.

**Comment by yuchongy1** [comment]
Hi,

Thanks for your reply.

I believe I have 
```python
assert timm.__version__ == "0.5.4"  # version check
```
in my code, which ensures the correct version?

**Comment by quanlin-wu** [comment]
Can you print the shape of tensor in 'models_vit.py'?
I want to know whether the bug happen before
'''
for blk in self.blocks:
            x = blk(x)
'''
or not.

**Comment by yuchongy1** [comment]
Sorry, I think I have the version check in the main but not in the models_vit.py,
but I suppose the check in the main.py should already ensure the timm is 0.5.4 for models_vit.py?

I put the print statement in Smooth.py, "_sample_noise" function,
just feeding "noisy" into self.base_classifier.

**Comment by quanlin-wu** [comment]
The bug happened when you want to evaluate the model on cifar10. Did
you run the pre-training or fine-tuning successfullly? If you directly run 'certfy_cifar10.py', the assert code may not take effect.
The shape of 'nosiy' is correct. It seems the problem lies in the norm layers in the model (the base classifier). Checking the shape of tensors in the vit model may help.

**Comment by yuchongy1** [comment]
The pre-training and finetuning can run without errors. I will check the shape in vit.
